# Generated by Django 3.2.16 on 2023-02-14 04:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0004_coursefeedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseFeedback",
        ),
    ]
